"""followers

Revision ID: 10198317fadc
Revises: c9f0573d2c6b
Create Date: 2020-06-07 06:08:54.526575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10198317fadc'
down_revision = 'c9f0573d2c6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Followers')
    # ### end Alembic commands ###
